version: '3'
volumes: 
    data:
services:
    web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - '.:/Miaowan'
        tty: true
        stdin_open: true
        environment:
            - 'DATABASE_PASSWORD=miaowan3030' 
        depends_on: 
            - db
        links:
            - db
    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        volumes:
            - 'data:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: miaowan3030